before_script:
    - which angr-test && angr-test sync hard

### local
angr:
    script: "angr-test angr"
    tags: [angr]

lint:
    script: "angr-test lint"
    tags: [angr]

### first level
fidget:
    script: "angr-test fidget"
    tags: [angr]

angrop:
    script: "angr-test angrop"
    tags: [angr]

topsecret:
    script: "angr-test top-secret"
    tags: [angr]

driller:
    script: "angr-test driller"
    tags: [angr]

tracer:
    script: "angr-test tracer"
    tags: [angr]

rex:
    script: "angr-test rex"
    tags: [angr]

colorguard:
    script: "angr-test colorguard"
    tags: [angr]

pwnrex:
    script: "angr-test pwnrex"
    tags: [angr]

patcherex:
    script: "angr-test patcherex"
    tags: [angr]

fuzzer:
    script: "angr-test fuzzer"
    tags: [angr]

docs:
    script: "angr-test docs"
    tags: [angr]

### Deploy stage

build_images:
    only: ["master"]
    stage: deploy
    script:
    - cgc-build worker
    - angr-build angr-ci
    tags: ["docker-builder"]
